
server:
  servlet:
    context-path: "/api/v1"
  port: 8090

spring:
  webflux:
    base-path: /api/v1
  jackson:
    default-property-inclusion: NON_EMPTY
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
    deserialization:
      fail-on-ignored-properties: false

  data:
    mongodb:
      auto-index-creation: true
      database: customerdb
      host: localhost
      port: 30001
      username: api_user
      password: api123
      replicaSetName: rs0



management:
  tracing:
    baggage:
      correlation:
        fields: correlationId



#logging.pattern.level: '%d{yyyy-MM-dd HH:mm:ss} cid:%X{correlationId} [%thread] %-5level %logger{36} - %msg%n'
