
server:
  servlet:
    context-path: "/api/v1"
  port: 8093

spring:
  webflux:
    base-path: /api/v1
  jackson:
    default-property-inclusion: NON_EMPTY
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
    deserialization:
      fail-on-ignored-properties: false

  data:
    - service:
        name: salesDatabase
        mongodb:
          autoIndexCreation: true
          database: salesdb
          host: localhost
          port: 30001
          username: api_user_cdc
          password: api123
          replicaSetName: rs0
    - service:
        name: inventoryDatabase
        mongodb:
          autoIndexCreation: true
          database: inventorydb
          host: localhost
          port: 30001
          username: api_user_cdc
          password: api123
          replicaSetName: rs0
    - service:
        name: customerDatabase
        mongodb:
          autoIndexCreation: true
          database: customerdb
          host: localhost
          port: 30001
          username: api_user_cdc
          password: api123
          replicaSetName: rs0

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG



management:
  tracing:
    baggage:
      correlation:
        fields: correlationId


