openapi: 3.0.3
info:
  title: Customer Service - OpenAPI 3.0
  description: |-
    This is a Customer Service

  contact:
    email: ashutoshkapoor1234@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost/
tags:
  - name: Customer
    description: Everything about your Customer
paths:
  /customers/{customerId}:
    get:
      tags:
        - Customer
      summary: Find customer by ID
      description: Returns a single customer
      operationId: getCustomerById
      parameters:
        - name: customerId
          in: path
          description: ID of customer to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomerResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Customer not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    put:
      tags:
        - Customer
      summary: Update the customer
      description: update a customer
      operationId: updateCustomer
      parameters:
        - name: customerId
          in: path
          description: ID of customer
          required: true
          schema:
            type: string
      requestBody:
        description: Update body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomerResponse'
        '404':
          description: Customer not found
        '405':
          description: Invalid input
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    delete:
      tags:
        - Customer
      summary: Delete the customer by Id
      description: Delete Customer for given Id
      operationId: deleteCustomer
      parameters:
        - name: customerId
          in: path
          description: ID of customer to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful operation
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /customers:
    post:
      tags:
        - Customer
      summary: Add a new customer
      description: Add a new customer
      operationId: createCustomer
      requestBody:
        description: Create customer body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomerResponse'
        '405':
          description: Invalid input
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    get:
      tags:
        - Customer
      summary: Get all customers
      description: Get all customers
      operationId: getCustomers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCustomersResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    delete:
      tags:
        - Customer
      summary: Delete all customers
      description: Delete all customers
      operationId: deletetCustomers
      responses:
        '204':
          description: successful operation
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'



components:
  schemas:
    GetCustomersResponse:
      type: array
      items:
        $ref: '#/components/schemas/CreateCustomerResponse'
    CreateCustomerRequest:
      type: object
      required:
        - firstName
        - lastName
        - email
        - amount
      properties:
        firstName:
          type: string
          example: Ashutosh
        lastName:
          type: string
          example: Kapoor
        email:
          type: string
          "format": "email"
          example: abc@gmail.com
        amount:
          type: number
          example: 22.40
    CreateCustomerResponse:
      type: object
      required:
        - firstName
        - lastName
        - email
        - id
        - amount
      properties:
        id:
          type: string
        firstName:
          type: string
          example: Ashutosh
        lastName:
          type: string
          example: Kapoor
        email:
          type: string
          "format": "email"
          example: abc@gmail.com
        amount:
          type: number
          example: 22.40

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
